export const cars = [
  {
    id: 1,
    year: 2022,
    month: 12,
    transmission: 'automatik',
    mileage: 124000,
    price: 14000,
    title: 'BMW 525D',
    link: 'bmw.jpg',
    images: [
      'bmw_back.jpg',
      'bmw_dashboard.jpg',
      'bmw_front.jpg',
      'bmw_interior.jpg',
    ],
    make: 'BMW',
    model: '525D',
    condition: 'NEU',
    drivetrain: 'rear-wheel',
    engine: '170KW',
    exteriror: 'grey',
  },
  {
    id: 2,
    year: 2018,
    month: 6,
    transmission: 'front-wheel',
    mileage: 24000,
    price: 8000,
    title: 'Mercedes-Benz E220',
    images: [
      'merc-front.jpg',
      'merc_back.jpg',
      'merc-interior.jpg',
      'merc-dashboard.jpg',
    ],
    link: 'merc220e.jpg',
    make: 'Mercedes-Benz',
    model: 'E220',
    condition: 'NEU',
    drivetrain: 'rear-wheel',
    engine: '200KW',
    exteriror: 'white',
  },
  {
    id: 3,
    year: 2017,
    month: 8,
    transmission: 'front-wheel',
    mileage: 154000,
    price: 24000,
    title: 'Audi e-tron',
    images: [
        'audi_back.jpg',
        'audi_dashboard.jpg',
        'audi_front.jpg',
        'audi_interior.jpg',
    ],
    link: 'audi.jpg',
    make: 'Audi',
    model: 'e-tron',
    condition: 'NEU',
    drivetrain: 'front-wheel',
    engine: '190KW',
    exteriror: 'white',
  },
  {
    id: 4,
    year: 2010,
    month: 10,
    transmission: 'rear-wheel',
    mileage: 224000,
    price: 18000,
    title: 'BMW 520D GRAND TURISMO',
    images: [
      'bmwgt_back.jpg',
      'bmwgt_dashboard.jpg',
      'bmw_frontgt.jpg',
      'bmwgt_interior.jpg',
    ],
    link: 'bmwgt.jpg',
    make: 'BMW',
    model: '520D',
    condition: 'NEU',
    drivetrain: 'rear-wheel',
    engine: '120KW',
    exteriror: 'grey',
  },
  {
    id: 5,
    year: 2016,
    month: 2,
    transmission: 'front-wheel',
    mileage: 4000,
    price: 20000,
    title: 'Ford Galaxy',
    link: 'ford.jpg',
    images: [
      'ford_interior.jpg',
      'ford_front.jpg',
      'ford_dashboard.jpg',
      'ford_back.jpg',
    ],
    make: 'Ford',
    model: 'Galaxy',
    condition: 'NEU',
    drivetrain: 'front-wheel',
    engine: '90KW',
    exteriror: 'white',
  },
];
